#!/usr/bin/env bash
pip install -r requirements-dev.txt && \
autopep8 -r --in-place --aggressive --max-line-length=79 apps && \
flake8 apps && \
python manage.py makemigrations  && \
python manage.py compilemessages  && \
python manage.py test
